apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
spec:
  selector:
    matchLabels:
      app: simple-flask-app
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: prathamj7/simple-flask-app
        ports:
        - containerPort: 5000

