apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app
spec:
  selector:
    app: simple-flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

